// Start a new video.  npm run new-video -- <slug> "Working title"
//
//   npm run new-video -- orion-vs-ix "Orion or Styletto IX — which one is actually for you?"
//
// Creates videos/<slug>/ and seeds 00-topic.md with the pipeline checklist. The three
// planning skills write the rest into the same folder:
//
//   videos/<slug>/00-topic.md    <- this script
//   videos/<slug>/01-research.md <- video-research skill
//   videos/<slug>/02-hook.md     <- video-hook skill
//   videos/<slug>/03-mindmap.md  <- video-mindmap skill  }  the board manifest
//   videos/<slug>/mindmap.json   <- video-mindmap skill  }
//
// The boards themselves land in boards/<slug>/, generated by scripts/<slug>/, scaffolded
// with `npm run new-board -- <slug>/<name>`.
import fs from "node:fs";
import path from "node:path";
import { ROOT, videoDir } from "../lib/paths.mjs";

const [slug, ...titleParts] = process.argv.slice(2);
const title = titleParts.join(" ").trim();

if (!slug || !/^[a-z0-9]+(-[a-z0-9]+)*$/.test(slug)) {
  console.error(
    'Usage: npm run new-video -- <slug> "Working title"\n' +
      '  e.g. npm run new-video -- orion-vs-ix "Orion or Styletto IX — which is for you?"\n\n' +
      "The slug is kebab-case and becomes videos/<slug>/, boards/<slug>/ and scripts/<slug>/.",
  );
  process.exit(1);
}

const dir = videoDir(slug);
const topicFile = path.join(dir, "00-topic.md");

if (fs.existsSync(topicFile)) {
  console.error(`Already exists: ${path.relative(ROOT, topicFile)}`);
  process.exit(1);
}

const today = new Date().toISOString().slice(0, 10);

fs.writeFileSync(
  topicFile,
  `VIDEO — ${title || slug}
${"=".repeat(Math.max(8, (title || slug).length + 8))}

SLUG: ${slug}
STARTED: ${today}
WORKING TITLE: ${title || "<fill in>"}

---

PIPELINE

- [ ] 0. video-topic     -> 00-topic.md      vidIQ demand evidence + the chosen title
- [ ] 1. video-research  -> 01-research.md   catalogue facts (live Supabase) + strategy brief
- [ ] 2. video-hook      -> 02-hook.md       the 30 seconds + what's on screen
- [ ] 3. video-mindmap   -> 03-mindmap.md    the connector map + board manifest
                            mindmap.json
- [ ] 4. figma-board-svg -> boards/${slug}/  generate, verify, read the PNGs
- [ ] 5. Import to FigJam, lay out on the col/row grid, draw the connectors
- [ ] 6. Record

Run the skills in order. Each one reads the file the previous one wrote.

---

NOTES

<anything Chintan says about this video that the skills should honour — scope,
a reframe, models in or out, something that must be on a board>
`,
);

console.log(`created  ${path.relative(ROOT, topicFile)}`);
console.log(`\nNext: run the video-research skill for "${title || slug}" (slug: ${slug}).`);
console.log(`It pulls the catalogue live from Supabase and writes 01-research.md.`);
